### ISSUE TITLE
Create main primary color variable

### ISSUE THREAD

**Issue by miguelmich** [cuartas15/proyecto#2]
# What
Please create a primary color variable in SASS so we can easily change the color scheme with a single value, it could be named like: `$primary-color: #FF2861;` and we must use this new variable color in the following elements:

![image](https://user-images.githubusercontent.com/662930/38451153-806d5512-39f0-11e8-9fd2-134abac8d3c4.png)

**Comment by cuartas15** [comment]
I extracted the hex colors from the image you provided using paint.net, and each one of those elements had a different hex code, so I assumed they used slightly different tones of red.
Your suggestion makes it easier though, so I'll do.

Thanks

**Comment by miguelmich** [comment]
Fixed on 870f87a
